<a href="https://colab.research.google.com/github/lucaspugliesso/curso_data_science/blob/master/Copia_de_Intro_a_Numpy_ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importa numpy

In [ ]:
import numpy as np

crea un numpy array que tenga la siguente estructura

```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```

llamalo `array`

In [ ]:
array= np.array([[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]])


averigua la forma del array

*array*.shape

In [ ]:
array.shape

(5, 3)

In [ ]:
array.ndim

2

Selecciona la segunda columna del array

In [ ]:
array[:,1]

array([ 6,  7,  8,  9, 10])

 Crea un vector con los valores del 15 al 55, llamalo array2
    
*pista: usa np.arange*

In [ ]:
array2 = np.arange(15, 56)
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

asigna el valor 23 a la quinta posicion del array2

In [ ]:
array2[4]=23
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

convierte array2 del revés (es decir `[55,54,....,15]`

In [ ]:
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

Crea una matriz diagonal donde los elementos de la diagonal sean los 5 primeros valores pares de array2, llamala `matriz_diag`

*pista: usa np.diag*

In [ ]:
valores_pares = array2[array2 % 2 == 0][:5]
valores_pares
# Crear una matriz diagonal con esos valores
matriz_diag = np.diag(valores_pares)

print(matriz_diag)


[[16  0  0  0  0]
 [ 0 18  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 22  0]
 [ 0  0  0  0 24]]


Imprime el numero de dimensiones de `matriz_diag`

In [ ]:
matriz_diag.ndim

2

Crea una matriz con números aleatorios de tamaño 5x3 (4 filas por 3 columnas), llamala `matriz`

In [ ]:
matriz= np.random.random ((5,3))
matriz

array([[0.4297528 , 0.27245285, 0.10916125],
       [0.71685754, 0.13568339, 0.76686425],
       [0.94468236, 0.1514848 , 0.24812084],
       [0.68856967, 0.33960189, 0.27818005],
       [0.97161794, 0.26140067, 0.53362746]])

multiplica `matriz` por `matriz_diag`

In [ ]:
matriz.T.shape

(3, 5)

In [ ]:
matriz.T

array([[0.4297528 , 0.71685754, 0.94468236, 0.68856967, 0.97161794],
       [0.27245285, 0.13568339, 0.1514848 , 0.33960189, 0.26140067],
       [0.10916125, 0.76686425, 0.24812084, 0.27818005, 0.53362746]])

In [ ]:
matriz.T @ matriz_diag

array([[ 6.87604477, 12.90343568, 18.89364727, 15.14853267, 23.31883056],
       [ 4.35924561,  2.4423011 ,  3.02969593,  7.47124158,  6.27361603],
       [ 1.74658002, 13.80355648,  4.96241678,  6.11996118, 12.80705896]])